<?php
/**
 * Created by PhpStorm.
 * User: yiyueqinghui
 * Date: 2018/5/17
 * Time: 12:01
 * title:构造函数  (   注意是__construct(){}  而非_construct(){}  )
 */
//具有构造函数的类会在每次创建新对象时先调用此方法，所以非常适合在使用对象之前做一些初始化工作。
class basic{
    function __construct(){
       echo "basic class <br/>";
    }
}

class flex extends basic{
    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        echo "flex class <br/>";
    }
}

class top extends basic{

}

$basic=new basic();
$flex=new flex();
$top=new top();